language: node_js
node_js:
  - "7.8.0"
env:
  ENVIRONMENT=PRODUCTION
notifications:
  email:
    recipients:
      - adbovenzo@gmail.com
    on_success: always
    on_failure: always
  slack:
    rooms:
      - pinkbit:wSmjgkF2TQJZLL1ytrmNzu9H#devops
    template:
      - "Build : %{repository_name} (%{commit}) -> %{author}: %{commit_subject} "
      - "Build Details: %{build_url}"
      - "Result: %{result} - Duration: %{duration}"
  on_success: always
  on_failure: always

before_install:
  - "npm install"

after_success:
	- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
  
service_name: travis-pro
repo_token: jFKOVuM3TUVpsvZZ6NQiR4faKvg0JOCLM